In [4]:
import numpy as np

In [13]:
#Double Dimention
a = np.array([[10,20,30],[40,50,110]])
b = np.array([[60,70,80],[90,100,120]])

#addition
print("Addition operater:\n", a+b)
print("Addition function:\n", np.add(a,b))

#substract
print("\nSubstraction Operater:\n", a-b)
print("Substraction function:\n", np.subtract(a,b))

#multiplication
print("\nMultiplication Operater:\n", a*b)
print("Multiplication Function:\n", np.multiply(a,b))

#division
print("\nDivision Operater:\n", a/b)
print("Division Function:\n", np.divide(a,b))

#module
print("\nModule operater:\n", a%b)
print("Module function:\n", np.mod(a,b))

#sum
print("\nSum of A:", np.sum(a))
print("Sum of B:", np.sum(b))

#max
print("\nMaximum of A:", np.max(a))
print("Maximum of B:", np.max(b))

#min
print("\nMinimum of A:", np.min(a))
print("Minimum of B:", np.min(b))

#mean
print("\nAverage of A:", np.mean(a))
print("Average of B:", np.mean(b))

Addition operater:
 [[ 70  90 110]
 [130 150 230]]
Addition function:
 [[ 70  90 110]
 [130 150 230]]

Substraction Operater:
 [[-50 -50 -50]
 [-50 -50 -10]]
Substraction function:
 [[-50 -50 -50]
 [-50 -50 -10]]

Multiplication Operater:
 [[  600  1400  2400]
 [ 3600  5000 13200]]
Multiplication Function:
 [[  600  1400  2400]
 [ 3600  5000 13200]]

Division Operater:
 [[0.16666667 0.28571429 0.375     ]
 [0.44444444 0.5        0.91666667]]
Division Function:
 [[0.16666667 0.28571429 0.375     ]
 [0.44444444 0.5        0.91666667]]

Module operater:
 [[ 10  20  30]
 [ 40  50 110]]
Module function:
 [[ 10  20  30]
 [ 40  50 110]]

Sum of A: 260
Sum of B: 520

Maximum of A: 110
Maximum of B: 120

Minimum of A: 10
Minimum of B: 60

Average of A: 43.333333333333336
Average of B: 86.66666666666667


In [14]:
#single dimention method
x=np.array([10,20,30,40,50,60,70,80,90,100])
print("dimention:", x.ndim) #dimetion method
print("shape", x.shape) #Shape method
print("Size of Length:", x.size) #Array Length
print("Type of Array:", x.dtype) #type of Array

dimention: 1
shape (10,)
Size of Length: 10
Type of Array: int64
