In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
b = np.array([[1,2,3],[2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [5]:
print("Dimention:", a.ndim)

Dimention: 1


In [6]:
print("B Dimention:", b.ndim) # ndim - dimention

B Dimention: 2


In [7]:
print("Shape: ", a.shape) #shape - containing value

Shape:  (5,)


In [9]:
print("Shape: ", b.shape) #(dimention, No. of Value)

Shape:  (2, 3)


In [10]:
print("size", a.size) # Length of size

size 5


In [11]:
print("size", b.size)

size 6


In [14]:
print("Type:", a.dtype) #dtype - type of array

Type: int64


In [15]:
print("Type:", b.dtype)

Type: int64


In [19]:
#Simple Arithmetic Operation
x=np.array([10,20,30])
y=np.array([1,2,3])
print("X + Y:", x+y)
print("X - Y:", x-y)
print("X * Y:", x*y)
print("X / Y:", x//y)

X + Y: [11 22 33]
X - Y: [ 9 18 27]
X * Y: [10 40 90]
X / Y: [10 10 10]


In [22]:
add = np.add(x,y) #addition function
print("addition", add)

#direct print
print("Substraction:", np.subtract(x,y)) #substract Function
print("Multiplication", np.multiply(x,y)) #multiply Function
print("Division", np.divide(x,y)) #divide Function
print("Module", np.mod(x,y)) #Module Function

addition [11 22 33]
Substraction: [ 9 18 27]
Multiplication [10 40 90]
Division [10. 10. 10.]
Module [0 0 0]


In [23]:
a= np.array([10,20,30,40,50])
print("Maximum value: ", np.max(a)) #maximum Function
print("Minimum value: ", np.min(a)) #minimum Function
print("total sum of value: ", np.sum(a)) #sum Function
print("Average value: ", np.mean(a)) #Average mean Function

Maximum value:  50
Minimum value:  10
total sum of value:  150
Average value:  30.0
