In [1]:
import numpy as np

In [3]:
b1 = np.array([[2,3],[4,5]])
b2 = np.array([[5,6],[7,8]])
print(b1)
print(b2)

[[2 3]
 [4 5]]
[[5 6]
 [7 8]]


In [4]:
a1 = np.arange(10, 100, 10)
print(a1)

[10 20 30 40 50 60 70 80 90]


In [15]:
import string

# Create a NumPy array of capital letters
capital_letters = np.array(list(string.ascii_uppercase))

print(capital_letters)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


In [9]:
zeroArray = np.zeros(10)
print(zeroArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
onesArray = np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
print(capital_letters.dtype)

<U1


In [19]:
#Random Function integer serie
print("Random Integer:\n", format(np.random.randint(1,5,10)))

Random Integer:
 [3 1 2 2 3 1 3 4 1 2]


In [21]:
a2 = np.arange(10)
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
oddarr = a2[a2%2 == 1]
print(oddarr)

[1 3 5 7 9]


In [24]:
a2[a2 % 2 == 1] = -1

print(a2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
