In [ ]:
# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import dataset and KNN classifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ---------------------------------------------------------
# STEP 1: Load Dataset
# ---------------------------------------------------------

# Load the famous Iris dataset (flower classification dataset)
iris = load_iris()

# Convert dataset into DataFrame for better understanding
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add target column (species)
df['species'] = iris.target

# Display first 5 rows
print("Dataset Preview:")
print(df.head())


# ---------------------------------------------------------
# STEP 2: Define Features and Target
# ---------------------------------------------------------

# Features (Independent variables)
X = iris.data

# Target (Dependent variable)
y = iris.target


# ---------------------------------------------------------
# STEP 3: Split Dataset into Training and Testing Data
# ---------------------------------------------------------

# 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print("\nTraining Data Size:", X_train.shape)
print("Testing Data Size:", X_test.shape)


# ---------------------------------------------------------
# STEP 4: Create KNN Model
# ---------------------------------------------------------

# Create KNN classifier with K = 3 neighbors
knn = KNeighborsClassifier(n_neighbors=3)

# Train the model using training data
knn.fit(X_train, y_train)


# ---------------------------------------------------------
# STEP 5: Make Predictions
# ---------------------------------------------------------

# Predict species for test data
y_pred = knn.predict(X_test)

print("\nPredicted Values:")
print(y_pred)


# ---------------------------------------------------------
# STEP 6: Evaluate Model Performance
# ---------------------------------------------------------

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nModel Accuracy:", accuracy)

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

'''A Confusion Matrix is a table used to evaluate the performance of a classification model.
It shows how many predictions were correct and incorrect by comparing actual values vs predicted values.
| Term                    | Meaning                                  |
| ----------------------- | ---------------------------------------- |
| True Positive (TP)      | Correctly predicted positive             |
| True Negative (TN)      | Correctly predicted negative             |
| False Positive (FP)     | Predicted positive but actually negative |
| False Negative (FN)     | Predicted negative but actually positive |

Calculate metrics like:

Accuracy

Precision : Precision measures how many predicted positive cases are actually correct.

Recall: Recall measures how many actual positive cases were correctly predicted.

F1-score: F1-score is the balance between precision and recall.
'''

# Detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


# ---------------------------------------------------------
# STEP 7: Predict New Data
# ---------------------------------------------------------

# Example new flower measurements
# Format: [sepal length, sepal width, petal length, petal width]

new_sample = [[5.1, 3.5, 1.4, 0.2]]

prediction = knn.predict(new_sample)

print("\nPrediction for new sample:", prediction)

# Convert numeric prediction to species name
print("Predicted Flower Type:", iris.target_names[prediction][0])

Dataset Preview:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  

Training Data Size: (120, 4)
Testing Data Size: (30, 4)

Predicted Values:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

Model Accuracy: 1.0

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00     