In [3]:
import numpy as np
array = np.array([[25,64],[45,23]])
print(np.sqrt(array)) # Square function

[[5.         8.        ]
 [6.70820393 4.79583152]]


In [8]:
print(array)
print("\nrows become Column:\n", array.T)  #rows become column and column become rows

[[25 64]
 [45 23]]

rows become Column:
 [[25 45]
 [64 23]]


In [13]:
b1 = np.array([[2,3],[4,5]])
b2 = np.array([[5,6],[7,8]])
#print(b1,"\n", b2)
matrix_multi = np.dot(b1, b2) #matrix multiplication function
print(matrix_multi)

[[31 36]
 [55 64]]


In [20]:
c1 = np.zeros([3,2]) # zeros Function
print(c1)
c1 = np.ones([3,2]) #ones function
print(c1, "\n",np.zeros(3))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]] 
 [0. 0. 0.]


In [24]:
bool = np.array([[True, True],[True, False]])
print("all() with axis 0:", np.all(bool))  #return true false value
print("all() with axis none:", np.all(bool,axis=0))

all() with axis 0: False
all() with axis none: [ True False]


In [38]:
#arange(start,stop,step)
a1 = np.arange(1, 10, 2)
print(a1)
a2 = np.arange(9)
print(a2)

#reshape matrix
reshape = a2.reshape(3,3)
print("Reshape:\n", reshape)

#third colum remove
result = reshape[:, :2]
print("Only two column Reshape:\n",result)

result = reshape[:2, :]
print("Only two Row Reshape:\n",result)

[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8]
Reshape:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Only two column Reshape:
 [[0 1]
 [3 4]
 [6 7]]
Only two column Reshape:
 [[0 1 2]
 [3 4 5]]


In [46]:
#vertically printing
x = np.array([[12,23],[23,43]])
y = np.array([[56,67],[78,89]])
z = np.array([[32,43],[54,65]])
print("X:\n",x,"\nY:\n", y, "\nZ:\n", z)

v= np.vstack((x,y,z)) #vstack combine vertically
print("Vertically vstack:\n", v)

h= np.hstack((x,y,z)) #hstack combine horizontally
print("Horizontally vstack:\n", h)

X:
 [[12 23]
 [23 43]] 
Y:
 [[56 67]
 [78 89]] 
Z:
 [[32 43]
 [54 65]]
Vertically vstack:
 [[12 23]
 [23 43]
 [56 67]
 [78 89]
 [32 43]
 [54 65]]
Horizontally vstack:
 [[12 23 56 67 32 43]
 [23 43 78 89 54 65]]


In [53]:
# Vertical and horizontal split
arrr = np.array([[1,2,3,4],[5,6,7,8]])
print(arrr)

vsplit = np.vsplit(arrr, 2)
print("\nVertically split\n", vsplit)

hsplit = np.hsplit(arrr, 2)
print("\nHorizontally split\n", hsplit)

[[1 2 3 4]
 [5 6 7 8]]

Vertically split
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

Horizontally split
 [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [61]:
jp = np.array([2,36,49,64])
print("Sqrt : ",np.sqrt(jp)) #squrt function
print("EXP : ", np.exp(jp)) #exponential function
print("sin : ", np.sin(jp)) #sin function
print("Cos : ", np.cos(jp)) #cos function
print("std : ", np.std(jp)) #standard division function

Sqrt :  [1.41421356 6.         7.         8.        ]
EXP :  [7.38905610e+00 4.31123155e+15 1.90734657e+21 6.23514908e+27]
sin :  [ 0.90929743 -0.99177885 -0.95375265  0.92002604]
Cos :  [-0.41614684 -0.12796369  0.30059254  0.39185723]
std :  22.895141405983935


In [67]:
#Random Function
print("random:", format(np.random.random(20)))

random: [0.92915781 0.03385404 0.17950209 0.43838056 0.50255399 0.07565882
 0.33321708 0.37289499 0.72370276 0.67133674 0.57275243 0.60538587
 0.98429684 0.36064536 0.28688053 0.61621439 0.88570996 0.98620901
 0.13981878 0.79025051]


In [69]:
#Random Function matrix
print("2d array random:\n", format(np.random.rand(3,4)))

2d array random:
 [[0.46191723 0.60015971 0.54383524 0.09796872]
 [0.72640258 0.65594019 0.97953341 0.8102189 ]
 [0.66539757 0.68938866 0.74665874 0.41764461]]


In [72]:
#Random Function integer serie
print("Random Integer:\n", format(np.random.randint(0,100,20)))

Random Integer:
 [32 61 34 12 99 70 42 47 79 69 68 44 80 97  1 61 68 48 79 29]


In [73]:
#Random Function Permutation
print("Permutation:\n", format(np.random.permutation(np.arange(20))))

Permutation:
 [15 13  7 12  8  9 14  6  1  3 19 16  0 17  2  5 10  4 18 11]
